package com.example.resouretree

import com.example.resouretree.data.transfer.TreeJson
import com.example.resouretree.domain.model.ActionType
import com.example.resouretree.domain.model.NodeType
import org.junit.Assert.*
import org.junit.Test
import java.io.File
import java.util.UUID

class BilibiliExportCompatibilityTest {
    @Test fun singleVideoSelectionDecodesWithCurrentTreeJson() {
        val sample = File("../tools/bilibili-export/samples/resourcetree-bilibili.single.sample.json")
        val codec = TreeJson()
        val dto = codec.decode(sample.readText(Charsets.UTF_8))
        assertEquals(1, dto.schemaVersion)
        assertEquals("哔哩哔哩", dto.roots.single().name)
        assertEquals("生产力", dto.roots.single().children.single().name)
        val nodes = codec.toNodes(dto)
        assertEquals(3, nodes.size)
        val item = nodes.single { it.type == NodeType.ITEM }
        assertEquals("示例视频 A", item.name)
        assertEquals("BVExample1", item.content)
        assertEquals(ActionType.COPY_AND_LAUNCH, item.action.type)
        assertEquals(item.content, item.action.text)
        assertEquals("tv.danmaku.bili", item.action.packageName)
        assertEquals(dto, codec.decode(codec.encode(dto)))
    }

    @Test fun userscriptGeneratedSampleDecodesWithCurrentTreeJson() {
        // Same deliverable generated by the real JS exporter from offline fixtures.
        val sample = File("../tools/bilibili-export/samples/resourcetree-bilibili.sample.json")
        val codec = TreeJson()
        val dto = codec.decode(sample.readText(Charsets.UTF_8))
        assertEquals(1, dto.schemaVersion)
        assertEquals("哔哩哔哩", dto.roots.single().name)
        assertEquals(listOf("生产力", "生命力"), dto.roots.single().children.map { it.name })
        val nodes = codec.toNodes(dto)
        assertEquals(3, nodes.count { it.type == NodeType.FOLDER })
        val items = nodes.filter { it.type == NodeType.ITEM }
        assertEquals(3, items.size)
        assertEquals(listOf("示例视频 A", "示例视频 B", "示例视频 C"), items.map { it.name })
        assertEquals(listOf("BVExample1", "BVExample2", "BVExample3"), items.map { it.content })
        items.forEach {
            assertEquals(ActionType.COPY_AND_LAUNCH, it.action.type)
            assertEquals(it.content, it.action.text)
            assertEquals("tv.danmaku.bili", it.action.packageName)
            assertTrue(it.tags.isEmpty())
        }
        assertEquals(nodes.size, nodes.map { it.id }.toSet().size)
        nodes.forEach { assertEquals(it.id, UUID.fromString(it.id).toString()) }
        assertEquals(dto, codec.decode(codec.encode(dto)))
        val reimported = codec.toNodes(dto, nodes.map { it.id }.toSet())
        assertTrue(reimported.none { fresh -> nodes.any { it.id == fresh.id } })
        assertEquals(3, reimported.count { it.type == NodeType.ITEM })
    }
}
